
server:
  port: 8080
  servlet:
    context-path: /

spring:
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/logistics?useUnicode=true&amp&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: a9530.A.
  jackson: # 时间格式转化
    date-format: yyyy-MM-dd HH:mm:ss

# mybatis-plus
mybatis-plus:
  type-aliases-package: com.yx.model
  mapper-locations: classpath:com/yx/dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



